### ISSUE TITLE
Remove the space before the headline section 

### ISSUE THREAD

**Issue by Ali-Khan5** [Arif1951995/may-14-task#1]
![image](https://user-images.githubusercontent.com/19200949/58167278-07927e80-7ca5-11e9-8c22-176d2a15e3f3.png)

your page has a space before  the first headline section , remove this as this is not according to the mockup image .

heres page for reference

![image](https://user-images.githubusercontent.com/19200949/58167542-97382d00-7ca5-11e9-9b21-731b4c3dc623.png)

**Comment by Arif1951995** [comment]
done
