### ISSUE TITLE
Change the services Icon to black and white versions 

### ISSUE THREAD

**Issue by Ali-Khan5** [Arif1951995/may-14-task#2]
As according to the mockup the icons used in the section is black ad white ,here the picture below
![image](https://user-images.githubusercontent.com/19200949/58167745-19285600-7ca6-11e9-9e75-87341144fc99.png)

while you have used colorful version of the logo
![image](https://user-images.githubusercontent.com/19200949/58167791-365d2480-7ca6-11e9-88d9-48057936668e.png)

replace with the non color versions .
Thank You

**Comment by Arif1951995** [comment]
done
