### ISSUE TITLE
Navbar Alignment issue 

### ISSUE THREAD

**Issue by Ali-Khan5** [Arif1951995/may-14-task#3]
Your navbar menu options has

- too big font size

- have too much space between the each menu option
here is your navbar
![image](https://user-images.githubusercontent.com/19200949/58168368-8ab4d400-7ca7-11e9-9cdf-8b657779c472.png)

Here is the mockup navbar for reference , you have to make it like this
![image](https://user-images.githubusercontent.com/19200949/58168496-da939b00-7ca7-11e9-9154-af81f27f3d26.png)

**Comment by Arif1951995** [comment]
done
